### ISSUE TITLE
datahub not loaded

### ISSUE THREAD

**Issue by wmegchel** [lidaof/eg-react#142]
Hi, 

when I try the example data hub URL:
https://epigenomegateway.wustl.edu/browser/?genome=hg19&hub=https://vizhub.wustl.edu/public/tmp/a.json

It does not load the bigwig files. I can see there are two tracks on ttps://vizhub.wustl.edu/public/tmp/a.json, which I can also download, but they are not loaded into the browser.

Similarly, my own data hub tracks are not loaded. What is going wrong? 

Thanks in advance, best,
Wout

**Comment by lidaof** [comment]
Hi @wmegchel , the tracks are loaded but not showing because that hub doesn't specify the option `showOnHubLoad` for the tracks, see https://eg.readthedocs.io/en/latest/datahub.html#showonhubload

if you open tracks-> custom tracks, you can see it's added to the tracks pool
![image](https://user-images.githubusercontent.com/102806/69354926-882b3b00-0c46-11ea-81e0-e217fcc85298.png)

we designed like this to avoid users load a hub with 100+ tracks and the paper will become slow, so in that way users can specify about 10-20 tracks for display by default.

**Comment by wmegchel** [comment]
Thanks, I missed that parameter :)
