### ISSUE TITLE
Data Fetch Failed Using Custom Tracks

### ISSUE THREAD

**Issue by ericaenjoy3** [lidaof/eg-react#144]
The [track file url](https://github.com/marcoralab/datahub/raw/master/summary_stats/Marioni2018_phase4.chrall.CPRA_b37.bw) (hg19) generated 'data fetch failed error' in 'Add custom track'. However, the same track works in the UCSC genome browser.

Would you please care to have look? Many thanks!

**Comment by lidaof** [comment]
Hi @ericaenjoy3 , sorry that the new browser currently don't support github urls since github doesn't allow Range request, the track can work with our old browser: http://epigenomegateway.wustl.edu/legacy/. You can also load this track from your local laptop without put them online with the [local track function](https://eg.readthedocs.io/en/latest/local.html) in the new browser. Feel free to let me any further question.

**Comment by ericaenjoy3** [comment]
Thanks for your prompt reply! And happy new year!

I have put the same track data to a different web server at [link](https://liuy22.u.hpc.mssm.edu/summary_stats/Marioni2018_phase4.chrall.CPRA_b37.bw), which supports range request. The custom track utility of the browser also failed to fetch the data with the same error. 

Would you please help? Warmly appreciated!

**Comment by lidaof** [comment]
Hi @ericaenjoy3 , I see the web server your have now supports range request. can you also add access control? would you mind try add the following to `apache2.conf` file and restart apache2 services? Thanks!
```
Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Headers: Range
Header always set Access-Control-Max-Age: 86400
```

**Comment by lidaof** [comment]
closing for now, feel free to reopen it or open a new issue.
