### ISSUE TITLE
How to fetch track files on the same server installed the web page using Docker

### ISSUE THREAD

**Issue by Eleven93** [lidaof/eg-react#166]
I have built up WashU on our lab's server using Docker. The web page is working, but I couldn't upload track files from local PC or from the server. I have checked the Docker container. It doesn't have an Apache installed. Then I installed Apache in the Docker container and add Header to its conf file, but it doesn't work. Could you please help me with that? Does WashU built up using Docker not depend on Apache? So, how to config CORS for it? How to load a track file from  the same server hosting WashU?

**Comment by lidaof** [comment]
Hi @Eleven93 that's because the browser is running on port 3000 and apache on port 80, there will be cors issue is ports are different. One way to resolve this is to set a reverse proxy on Apache when visiting :80/browser proxy to :3000/browser. You can google that setup, is pretty popular.

The way we did for the WashU Epigenome Browser is we use the built code after `npm run build`, we use the gene API hosted on Amazon Lambda API, so we can put the built html files anywhere to be hosted.

Hope this helps, feel free to let me any issue.

**Comment by Eleven93** [comment]
Thanks a lot! I will have a try!
